# Generated by Django 5.2.4 on 2025-07-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='100文字以内で入力してください', max_length=100, verbose_name='タイトル'),
        ),
    ]
